[package]
name = "poc3"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = { version = "0.13", features = ["tiles", "vulkan"] }
amethyst-imgui = { git = "https://github.com/amethyst/amethyst-imgui.git" }
serde = { version = "1.0.104", features = ["derive"] }
ron = "0.5.1"
